-- 108 · teams.org_id NOT NULL 해제 (조직 개념 폐기의 마지막 잔재 정리)
--
-- 왜: CEO 콘솔(/admin)에서 팀을 만들 수 없다. `POST /api/admin/teams` 가 501 을 돌려주고,
--     실제로 팀을 만들려면 운영자가 로컬에서 `node scripts/onboard-club.mjs ... --commit`
--     을 돌려야 한다(어드민 콘솔 감사 03 항목). 501 의 유일한 이유가 이 NOT NULL 이다 —
--     teams 한 줄을 만들려면 먼저 orgs 한 줄을 만들어야 하는데, 그 orgs 는 앱이 아무도
--     읽지 않는 죽은 배관이라 화면에서 물어볼 값이 없다.
--
-- 무엇을: teams.org_id 의 NOT NULL 만 푼다. 컬럼도, FK 도, 기존 값도 그대로 둔다.
--         (순수 완화 — 기존 행/코드에 대한 파괴적 변경이 0이다.)
--
-- 왜 안전한가 — 근거 셋:
--   1) 조직(org) 개념은 2026-08-06 에 폐기됐다. **팀이 최상위 단위**이고 로스터·회원계정을
--      팀이 직접 갖는다. orgs 테이블은 074_orgs_and_team_fk.sql 이 만든 뒤로 FK 를
--      만족시키기 위해서만 존재한다.
--      → scripts/onboard-club.mjs 헤더 주석이 같은 사실을 적어두고 있다:
--        "orgs 테이블 자체는 앱 어디서도 읽지 않는다(grep 로 확인됨) — FK 를 만족시키기
--         위한 내부 배관일 뿐이다."
--   2) `org_id` 는 src/ 전체에서 참조가 2건뿐이고, **둘 다 주석**이다
--      (src/app/api/admin/teams/route.ts 의 501 사유 설명 — 이번 작업에서 그 501 을
--      없애면서 함께 정리된다). 즉 이 값을 읽는 실행 코드가 0줄이다.
--      팀 URL 은 org_id 가 아니라 (org_slug, sub_slug) 복합키로 푼다(teams_org_sub_unique).
--   3) NOT NULL 을 푸는 것은 제약 **완화**다. 기존 행은 전부 org_id 가 채워진 채 남고,
--      FK(teams_org_id_fkey)도 그대로라 값이 들어오면 여전히 orgs 를 참조하도록 강제된다.
--      NULL 을 허용할 뿐, 아무것도 깨뜨리지 않는다.
--      (참고: onboard-club.mjs 는 계속 orgs 행을 만들어 org_id 를 채운다 — 이 마이그레이션
--       이후에도 그 스크립트는 그대로 동작한다. 새 콘솔 경로만 NULL 을 쓴다.)
--
-- 이후 무엇이 달라지나:
--   `POST /api/admin/teams` 가 org_id 를 아예 넣지 않고 팀을 만든다 → 죽은 orgs 행이
--   더 이상 늘지 않는다. 이 마이그레이션을 적용하지 않으면 그 API 는 NOT NULL 위반(23502)
--   을 감지해 "DB 준비가 필요합니다 — 마이그레이션 108 을 적용하세요" 를 503 으로 돌려준다
--   (조용한 500 이 아니라 무엇을 해야 하는지 알려주는 실패).
--
-- 정리하지 않은 것(의도적):
--   orgs 테이블 자체와 남아 있는 org_id 값은 그대로 둔다. DROP 은 되돌릴 수 없고,
--   지금 얻을 이득이 없다. 폐기는 별도 회차에서 판단한다.
--
-- ⚠️ 이 파일은 작성만 하고 실행하지 않는다 (ALTER TABLE = 위험 키워드,
--    CLAUDE.md 규칙상 사용자 명시 확인 후에만 실행).
--    사용자 확인 후 `scripts/db-migrate.mjs` 또는 Supabase SQL Editor 로 적용.
--
-- ── 롤백 ──────────────────────────────────────────────────────────────
--   ⚠ 되돌리려면 org_id 가 NULL 인 팀이 하나도 없어야 한다. 이 마이그레이션 이후
--     콘솔에서 만든 팀은 전부 NULL 이므로, 먼저 그 팀들에 orgs 행을 만들어 채우거나
--     삭제해야 한다. 그 상태에서만:
--       ALTER TABLE teams ALTER COLUMN org_id SET NOT NULL;
-- ─────────────────────────────────────────────────────────────────────

ALTER TABLE public.teams ALTER COLUMN org_id DROP NOT NULL;
